---
title: "Research"
---
### Publications

**The Net-Narrowing Potential of Diversion: A Theoretical and Empirical Assessment of Prosecutor-led Adult Diversion.** *Forthcoming in Criminology.* (with Viet Nguyen) [[Paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4083068)
[[White paper]](https://github.com/phillydao/phillydao-public-data/raw/main/docs/reports/AMP_Whitepaper.pdf)

**The Role of Case Management in Misdemeanor Prosecution.** *Criminology, 64*, 402–449 (2026). (with Aurélie Ouss) [[Paper]](https://doi.org/10.1111/1745-9125.70033) [[White Paper]](white_papers/The Role of Case Management in Low-level Prosecution.pdf) [[Replication Data & Code]](https://doi.org/10.7910/DVN/KX7VIV)

**Systemic Failure to Appear in Court.** *University of Pennsylvania Law Review, 172*(1) (2023). (with Sandy Mayson, Megan Stevenson, and Aurélie Ouss) [[Paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4558056) [[White Paper]](https://www.law.upenn.edu/live/files/13151-court-no-shows-a-systemic-issue)

- **Public Writing:** [\[Philadelphia Inquirer Op-Ed\]](https://www.inquirer.com/opinion/commentary/philadelphia-police-officers-failure-to-appear-court-20231201.html) [\[Law360 Op-Ed\]](https://www.law360.com/articles/1837604)
- **Media Coverage:** [\[ABA Journal\]](https://www.abajournal.com/web/article/private-criminal-defense-lawyers-fail-to-show-up-for-their-cases-more-often-than-defendants-study-finds) [\[Advancing Pretrial Policy and Research\]](https://advancingpretrial.org/story/showing-up-for-court/) [\[Philadelphia Inquirer\]](https://www.inquirer.com/news/philadelphia/philadelphia-police-video-surveillance-drug-arrests-20240508.html)


### Working Papers

**Bench Warrants as an Institutional Response to Failure to Appear**  
(with Michael Zanger-Tishler)  
*Revise and Resubmit at the Journal of Legal Studies*

**Prosecutors as Case Managers**  
*Revise and Resubmit at Law & Society Review*

### Ongoing Research

**Personnel and Policy: Disentangling Mechanisms in Prosecutorial Change**  
(with Aurélie Ouss, Marit Rehavi, and Eden Ralph)

**Prosecutor Backgrounds and Charging Decisions**  
(with Paul Heaton and Greg Ridgeway)
